### ISSUE TITLE
Scala 2.12 support for ElasticSearch

### ISSUE THREAD

**Issue by LorenzBuehmann** [SANSA-Stack/SANSA-DataLake#13]
We're planning to move to Scala 2.12 in the long term and also do support Scala 2.11 and 2.12 and with the next major SANSA release. Basically all code and dependencies have been adapted, the only thing are 3rd party dependencies that do have a Scala 2.12 release. In particular, Datalake depends on several Spark connectors for the different data sources. Among others, ElasticSearch is supported, which unfortunately has no Spark connector for Scala 2.12 yet.

There has been discussion for a Scala 2.12 release of the ElasticSearch Connector, but for some reason it's stuck now for month: https://github.com/elastic/elasticsearch-hadoop/issues/1224

We should do

- [ ] ping the devs on their Github issue 
- [x] drop the ElasticSearch support for the Scala 2.12 release - this in fact needs some refactoring I guess, given that now it's more or less hard-coded and a more component oriented approach similar to OSGi or the Jena services

That said, we should also add some documentation about the supported data source + their corresponding version.

**Comment by mnmami** [comment]
Hi Lorenz, 

Thanks for following up with this.

I personally am ok with dropping the support for Elasticsearch till 2.12 version is made available. If that is also ok for the others, I will do the necessary. It's actually not a lot of work, we just remove the `case` for Elasticsearch connection [here](https://github.com/SANSA-Stack/SANSA-DataLake/blob/develop/sansa-datalake-spark/src/main/scala/net/sansa_stack/datalake/spark/SparkExecutor.scala#L92), then we are safe to remove the dependency from the POM file.
