### ISSUE TITLE
Add possibility to read configuration files from S3

### ISSUE THREAD

**Issue by GezimSejdiu** [SANSA-Stack/SANSA-DataLake#4]
Hi @mnmami ,

I already gave short info about this concern [here](https://github.com/SANSA-Stack/SANSA-DataLake/issues/1#issuecomment-470559366), but better to open an issue about this thread as you [suggested already](https://github.com/SANSA-Stack/SANSA-DataLake/issues/1#issuecomment-470567659).

Just to have the info as a reference, I will post my comment here as well : 

> Just wanted to add another concern here. You already provided the possibility to detect if the path is coming from HDFS or file system (which is great) but maybe consider [my suggestion](https://github.com/SANSA-Stack/SANSA-DataLake/issues/1#issue-393415615) from the beginning of the thread. I'm saying this since users may use different storages (e.g. S3, Alluxio, ... which Spark can read from). We had one use case with Alethio and they used S3 as their storage.

Best regards,

**Comment by mnmami** [comment]
For the information, data (files) can already be read from an S3 bucket, as we pass the file path as-is to the DataFrame creation component. See [here](https://github.com/SANSA-Stack/SANSA-DataLake/blob/develop/sansa-datalake-spark/src/main/scala/net/sansa_stack/datalake/spark/SparkExecutor.scala#L80) for an example. The file path is given the config file. What needs to be addressed here I think is reading the config files (config, mappings, query) from those storage formats.

**Comment by mnmami** [comment]
I renamed this to be specific on which format to support. We open one issue per storage format.
